tap 'caskroom/cask'
tap 'homebrew/binary'
tap 'homebrew/bundle'
tap 'homebrew/dupes'
tap 'homebrew/versions'
brew 'git'
brew 'mackup'
brew 'openssl'
brew 'nmap'
brew 'pandoc'
brew 'wget'
# ここからbrew/cask
brew 'caskroom/cask/brew-cask'
# 日本語入力
cask 'google-japanese-ime'
# iPadやiPhoneをMacのサブディスプレイにするソフト（iOSアプリが有料なので注意）
# cask 'duet'
# SSH Tunnel
cask 'coccinellida'
# エディタ
cask 'atom'
cask 'coteditor'
# FTP/SFTP
cask 'cyberduck'
cask 'filezilla'
# メモ帳
cask 'evernote'
# Qiita用ツール
cask 'kobito'
# ブラウザ
cask 'firefox'
cask 'google-chrome'
# git
cask 'github-desktop'
cask 'sourcetree'
# クラウドストレージ
cask 'google-drive'
# IDE
cask 'java'
cask 'netbeans-php'
# 開発用ツール
# 仮想環境
cask 'vagrant'
cask 'virtualbox'
cask 'packer'
# Chef開発
cask 'chefdk'
# DB開発
cask 'sequel-pro'
# チャットツール
cask 'skype'
# マシンをスリープさせない
cask 'insomniax'
# スクリーンショット
cask 'skitch'
# ウインドウのサイズ整理
cask 'spectacle'
# ブラウザ間ブックマーク同期
cask 'xmarks-safari'
# OS設定変更拡張
cask 'onyx'
# アプリケーション削除
cask 'appcleaner'
# Adobe関連
cask 'flash'
cask 'adobe-reader'
cask 'adobe-air'
cask 'adobe-creative-cloud'
cask 'adobe-creative-cloud-cleaner-tool'
